# -*- coding: utf-8 -*-
# -*- mode: org -*-

#+STARTUP: overview indent
#+LANGUAGE: pt_BR
#+OPTIONS:   toc:nil
#+TAGS: noexport(n) deprecated(d) ignore(i)
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport

#+TITLE: Boas Práticas Experimentais para a Escola Regional de Alto Desempenho
#+AUTHOR:    Lucas Mello Schnorr, Vinícius Garcia Pinto
#+EMAIL:     {schnorr, vgpinto}@inf.ufrgs.br

Este material acompanha os minicurso/tutorial

- *Boas Práticas para Experimentos Computacionais em Clusters* da ERAD/RS 2019 (Três de Maio - RS)
- *Projeto Experimental para Prática com Alto Desempenho* da ERAD/SP 2019 (Campinas - SP)

O material foi preparado na forma de um tutorial auto-guiado para
exercitar, em cenários estimulados, algumas partes das boas práticas
apresentadas no minicurso e tutorial. Ele é dividido em quatro partes,
sugeridas nesta ordem:

* Tutoriais

*Objetivo deste Tutorial*: O objetivo é fazer um projeto experimental
para analisar o desempenho (tempo de execução e speedup) de um
programa de multiplicação de matrizes escrito em MPI. O desempenho
será analisado em função de diferentes versões da implementação
OpenMPI e quantidade de processos.

- #0 [[./0_Programa_Teste.org][Programa Teste]]
- #1 [[./1_Ferramentas.org][Instalação de Ferramentas com Spack]]
- #2 [[./2_Experimentos.org][Realização de Experimentos Computacionais]]
- #3 [[./3_Analise.org][Análise de Dados]]
- #4 [[./4_Graficos.org][Criação de Gráficos]]

* Ambiente

Veja mais informações sobre [[./ambiente.org][como o ambiente =docker= foi preparado]].

* Autoria

- [[http://www.inf.ufrgs.br/~schnorr][Prof. Lucas (http://www.inf.ufrgs.br/~schnorr)]]
- [[http://www.inf.ufrgs.br/~vgpinto][Prof. Vinícius (http://www.inf.ufrgs.br/~vgpinto)]]
* Melhorias                                                        :noexport:

Constatações observadas

- [ ] A compilação do hwloc do spack (e mesmo dentro do slurm no PCAD)
  levou muito muito muito tempo. Mesmo após 2hs, a compilação não
  terminou.
- [ ] O container docker só complicou as coisas (e ocupou 1h para
  baixar). Os alunos não sabiam se deveriam fazer no container ou na
  plataforma.
- [ ] As alocações no cluster foram problemáticas, alunos ficarão
  esperando por um tempão até os nós serem liberados. 
- [ ] Alguns alunos com pouca experiência em Linux não sabiam
  requisitos mínimos.

Modificações sugeridas

- [ ] Trocar o NAS por uma aplicação bem simples (multiplicação de
  matriz) cuja execução nos nós seja bastante rápido, utilizando
  somente processos (sem threads).
- [ ] Simplificar o spack usando algo mais simples de compilar (zlib,
  com duas parametrizações).
- [ ] Adicionar a instalação "prévia" de duas versões de OpenMPI
  (versão 3. e 2, por exemplo) e incluir isso no projeto experimental
  para estudar como fator apenas 1 versão da aplicação com 1 entrada e
  uma certa quantidade de processos (de 1 até n cores) e as duas
  versões do MPI, fazendo somente 5 replicações.
- [ ] No Slurm, oferecer diretamente o script sem passar pela parte
  "manual".
- [ ] O docker seria utilizado, opcionalmente, somente na parte da
  análise dos dados (tutoriais 3 e 4).
